### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by aderzelle** [warrenlr/LINKS#13]
Hello, 
I am unable to compile the bloom filter
`g++ -c BloomFilter_wrap.cxx -I/usr/lib/perl5/core_perl/CORE -fPIC -Dbool=char -O3`

This returns

```
In file included from /usr/include/c++/7.1.1/cmath:42:0,
                 from /usr/include/c++/7.1.1/math.h:36,
                 from BloomFilter_wrap.cxx:758:
/usr/include/c++/7.1.1/bits/cpp_type_traits.h:145:12: error: redefinition of ‘struct std::__is_integer<char>’
     struct __is_integer<char>
            ^~~~~~~~~~~~~~~~~~
/usr/include/c++/7.1.1/bits/cpp_type_traits.h:138:12: note: previous definition of ‘struct std::__is_integer<char>’
     struct __is_integer<bool>
            ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7.1.1/exception:142:0,
                 from /usr/include/c++/7.1.1/stdexcept:38,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/bits/exception_ptr.h: In member function ‘std::__exception_ptr::exception_ptr::operator char() const’:
/usr/include/c++/7.1.1/bits/exception_ptr.h:145:16: error: invalid conversion from ‘void*’ to ‘char’ [-fpermissive]
       { return _M_exception_object; }
                ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7.1.1/bits/move.h:54:0,
                 from /usr/include/c++/7.1.1/bits/nested_exception.h:40,
                 from /usr/include/c++/7.1.1/exception:143,
                 from /usr/include/c++/7.1.1/stdexcept:38,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/type_traits: At global scope:
/usr/include/c++/7.1.1/type_traits:230:12: error: redefinition of ‘struct std::__is_integral_helper<char>’
     struct __is_integral_helper<char>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7.1.1/type_traits:226:12: note: previous definition of ‘struct std::__is_integral_helper<char>’
     struct __is_integral_helper<bool>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7.1.1/exception:143:0,
                 from /usr/include/c++/7.1.1/stdexcept:38,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/bits/nested_exception.h: In member function ‘void std::nested_exception::rethrow_nested() const’:
/usr/include/c++/7.1.1/bits/nested_exception.h:69:11: error: invalid user-defined conversion from ‘const std::__exception_ptr::exception_ptr’ to ‘bool’ [-fpermissive]
       if (_M_ptr)
           ^~~~~~
In file included from /usr/include/c++/7.1.1/exception:142:0,
                 from /usr/include/c++/7.1.1/stdexcept:38,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/bits/exception_ptr.h:144:16: note: candidate is: std::__exception_ptr::exception_ptr::operator char() const <near match>
       explicit operator bool() const
                ^~~~~~~~
/usr/include/c++/7.1.1/bits/exception_ptr.h:144:16: note:   return type ‘char’ of explicit conversion function cannot be converted to ‘bool’ with a qualification conversion
In file included from /usr/include/c++/7.1.1/bits/basic_string.h:6385:0,
                 from /usr/include/c++/7.1.1/string:52,
                 from /usr/include/c++/7.1.1/stdexcept:39,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/bits/functional_hash.h: At global scope:
/usr/include/c++/7.1.1/bits/functional_hash.h:127:3: error: redefinition of ‘struct std::hash<char>’
   _Cxx_hashtable_define_trivial_hash(char)
   ^
/usr/include/c++/7.1.1/bits/functional_hash.h:124:3: note: previous definition of ‘struct std::hash<char>’
   _Cxx_hashtable_define_trivial_hash(bool)
   ^
In file included from /usr/include/c++/7.1.1/bits/uniform_int_dist.h:35:0,
                 from /usr/include/c++/7.1.1/bits/stl_algo.h:66,
                 from /usr/include/c++/7.1.1/algorithm:62,
                 from BloomFilter_wrap.cxx:1615:
/usr/include/c++/7.1.1/limits:452:12: error: redefinition of ‘struct std::numeric_limits<char>’
     struct numeric_limits<char>
            ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7.1.1/limits:383:12: note: previous definition of ‘struct std::numeric_limits<char>’
     struct numeric_limits<bool>
            ^~~~~~~~~~~~~~~~~~~~

```

If I keep going with the install process, the next step seems to work but attempt at testing returns

`/usr/bin/perl: symbol lookup error: /home/alessandro/tools/links_v1.8.5/lib/bloomfilter/swig/BloomFilter.so: undefined symbol: Perl_Gthr_key_ptr`

Any idea? 

Thanks

**Comment by warrenlr** [comment]
this is typically caused by incompatibility between the CORE and your current/default PERL.  Refer to: https://github.com/warrenlr/LINKS/issues/9      

Is /usr/lib/perl5/core_perl/CORE the correct path matching your version of PERL?

**Comment by aderzelle** [comment]
It is the path where I find the EXTERN.h file. 
I am using perl 5.26

**Comment by aderzelle** [comment]
In fact I have another CORE path but there is no EXTERN.h in it.

**Comment by warrenlr** [comment]
Are there other PERL versions you could test/install?  The default, /usr/bin/perl is 5.26?  
Swig didn't return any errors when building BloomFilter_wrap.cxx ?

**Comment by aderzelle** [comment]
Swig didn't complain, however I have to say
`preinst-swig -Wall -c++ -perl5 BloomFilter.i
`
did not work (command not foundà, however

`swig -Wall -c++ -perl5 BloomFilter.i
`
But I thought it was a typo in the tutorial.

I have perlbrew, I am gonna install another version and test it.

**Comment by warrenlr** [comment]
also, make sure that you either change the shebang line in "test.pl" and "LINKS" to match your version of PERL (or invoke the specific version of the PERL interpreter you used to build the module, before the script)

**Comment by aderzelle** [comment]
Hello again,
so I tried with Perl-16 installed with perlbrew
`g++ -c BloomFilter_wrap.cxx -I/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE -fPIC -Dbool=char -O3`

This returns an error but seems to be a different one

```
In file included from /home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/perl.h:3441:0,
                 from BloomFilter_wrap.cxx:763:
/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/pad.h:236:8: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
        "Pad 0x%"UVxf"[0x%"UVxf"] set_cur    depth=%d\n", \
        ^
/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/pad.h:236:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
        "Pad 0x%"UVxf"[0x%"UVxf"] set_cur    depth=%d\n", \
                     ^
/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/pad.h:254:8: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
        "Pad 0x%"UVxf"[0x%"UVxf"] save_local\n",  \
        ^
/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/pad.h:254:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
        "Pad 0x%"UVxf"[0x%"UVxf"] save_local\n",  \
                     ^
/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/pad.h:262:8: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
        "Pad 0x%"UVxf"[0x%"UVxf"] restore_local\n", \
        ^
/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/pad.h:262:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
        "Pad 0x%"UVxf"[0x%"UVxf"] restore_local\n", \
                     ^
In file included from BloomFilter_wrap.cxx:763:0:
/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/perl.h:4215:8: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   INIT("Use of uninitialized value%"SVf"%s%s");
        ^
/home/alessandro/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/CORE/perl.h:4235:8: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   INIT("Modification of non-creatable hash value attempted, subscript \"%"SVf"\"");
        ^
In file included from /usr/include/c++/7.1.1/cmath:42:0,
                 from /usr/include/c++/7.1.1/math.h:36,
                 from BloomFilter_wrap.cxx:758:
/usr/include/c++/7.1.1/bits/cpp_type_traits.h:145:12: error: redefinition of ‘struct std::__is_integer<char>’
     struct __is_integer<char>
            ^~~~~~~~~~~~~~~~~~
/usr/include/c++/7.1.1/bits/cpp_type_traits.h:138:12: note: previous definition of ‘struct std::__is_integer<char>’
     struct __is_integer<bool>
            ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7.1.1/exception:142:0,
                 from /usr/include/c++/7.1.1/stdexcept:38,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/bits/exception_ptr.h: In member function ‘std::__exception_ptr::exception_ptr::operator char() const’:
/usr/include/c++/7.1.1/bits/exception_ptr.h:145:16: error: invalid conversion from ‘void*’ to ‘char’ [-fpermissive]
       { return _M_exception_object; }
                ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7.1.1/bits/move.h:54:0,
                 from /usr/include/c++/7.1.1/bits/nested_exception.h:40,
                 from /usr/include/c++/7.1.1/exception:143,
                 from /usr/include/c++/7.1.1/stdexcept:38,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/type_traits: At global scope:
/usr/include/c++/7.1.1/type_traits:230:12: error: redefinition of ‘struct std::__is_integral_helper<char>’
     struct __is_integral_helper<char>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7.1.1/type_traits:226:12: note: previous definition of ‘struct std::__is_integral_helper<char>’
     struct __is_integral_helper<bool>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7.1.1/exception:143:0,
                 from /usr/include/c++/7.1.1/stdexcept:38,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/bits/nested_exception.h: In member function ‘void std::nested_exception::rethrow_nested() const’:
/usr/include/c++/7.1.1/bits/nested_exception.h:69:11: error: invalid user-defined conversion from ‘const std::__exception_ptr::exception_ptr’ to ‘bool’ [-fpermissive]
       if (_M_ptr)
           ^~~~~~
In file included from /usr/include/c++/7.1.1/exception:142:0,
                 from /usr/include/c++/7.1.1/stdexcept:38,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/bits/exception_ptr.h:144:16: note: candidate is: std::__exception_ptr::exception_ptr::operator char() const <near match>
       explicit operator bool() const
                ^~~~~~~~
/usr/include/c++/7.1.1/bits/exception_ptr.h:144:16: note:   return type ‘char’ of explicit conversion function cannot be converted to ‘bool’ with a qualification conversion
In file included from /usr/include/c++/7.1.1/bits/basic_string.h:6385:0,
                 from /usr/include/c++/7.1.1/string:52,
                 from /usr/include/c++/7.1.1/stdexcept:39,
                 from BloomFilter_wrap.cxx:1569:
/usr/include/c++/7.1.1/bits/functional_hash.h: At global scope:
/usr/include/c++/7.1.1/bits/functional_hash.h:127:3: error: redefinition of ‘struct std::hash<char>’
   _Cxx_hashtable_define_trivial_hash(char)
   ^
/usr/include/c++/7.1.1/bits/functional_hash.h:124:3: note: previous definition of ‘struct std::hash<char>’
   _Cxx_hashtable_define_trivial_hash(bool)
   ^
In file included from /usr/include/c++/7.1.1/bits/uniform_int_dist.h:35:0,
                 from /usr/include/c++/7.1.1/bits/stl_algo.h:66,
                 from /usr/include/c++/7.1.1/algorithm:62,
                 from BloomFilter_wrap.cxx:1615:
/usr/include/c++/7.1.1/limits:452:12: error: redefinition of ‘struct std::numeric_limits<char>’
     struct numeric_limits<char>
            ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7.1.1/limits:383:12: note: previous definition of ‘struct std::numeric_limits<char>’
     struct numeric_limits<bool>
            ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7.1.1/cassert:44:0,
                 from ../BloomFilter.hpp:19,
                 from BloomFilter_wrap.cxx:1999:
../BloomFilter.hpp: In member function ‘void BloomFilter::storeFilter(const string&) const’:
../BloomFilter.hpp:315:3: error: invalid user-defined conversion from ‘std::ofstream {aka std::basic_ofstream<char>}’ to ‘bool’ [-fpermissive]
   assert(myFile);
   ^
In file included from /usr/include/c++/7.1.1/ios:44:0,
                 from /usr/include/c++/7.1.1/istream:38,
                 from /usr/include/c++/7.1.1/fstream:38,
                 from ../BloomFilter.hpp:15,
                 from BloomFilter_wrap.cxx:1999:
/usr/include/c++/7.1.1/bits/basic_ios.h:117:16: note: candidate is: std::basic_ios<_CharT, _Traits>::operator char() const [with _CharT = char; _Traits = std::char_traits<char>] <near match>
       explicit operator bool() const
                ^~~~~~~~
/usr/include/c++/7.1.1/bits/basic_ios.h:117:16: note:   return type ‘char’ of explicit conversion function cannot be converted to ‘bool’ with a qualification conversion
In file included from /usr/include/c++/7.1.1/cassert:44:0,
                 from ../BloomFilter.hpp:19,
                 from BloomFilter_wrap.cxx:1999:
../BloomFilter.hpp:322:3: error: invalid user-defined conversion from ‘std::ofstream {aka std::basic_ofstream<char>}’ to ‘bool’ [-fpermissive]
   assert(myFile);
   ^
In file included from /usr/include/c++/7.1.1/ios:44:0,
                 from /usr/include/c++/7.1.1/istream:38,
                 from /usr/include/c++/7.1.1/fstream:38,
                 from ../BloomFilter.hpp:15,
                 from BloomFilter_wrap.cxx:1999:
/usr/include/c++/7.1.1/bits/basic_ios.h:117:16: note: candidate is: std::basic_ios<_CharT, _Traits>::operator char() const [with _CharT = char; _Traits = std::char_traits<char>] <near match>
       explicit operator bool() const
                ^~~~~~~~
/usr/include/c++/7.1.1/bits/basic_ios.h:117:16: note:   return type ‘char’ of explicit conversion function cannot be converted to ‘bool’ with a qualification conversion

```

**Comment by warrenlr** [comment]
@benvvalk, any idea? Could this be due to the g++ compiler?

**Comment by benvvalk** [comment]
@warrenlr I've been googling around a bit but unfortunately I don't have any good guesses.

It seems that SWIG is generating code that doesn't compile with the system's C++ compiler.

@aderzelle: Out of curiosity, are you running on Linux or Mac? Do you have multiple versions of g++ installed? Could you show the output of `g++ --version`?

**Comment by aderzelle** [comment]
I am running Manjaro Linux. 
Here it is! 
`g++ (GCC) 7.1.1 20170630
`

**Comment by benvvalk** [comment]
Thank you @aderzelle.  I'm not sure what to try next unfortunately.

**Comment by txje** [comment]
@aderzelle I get those errors when I try to compile with g++ 6.3.0, but 4.8.5 works fine. I'm not sure exactly where in there the problem lies, but I'd just try a version pre-6.0.

I ran into another problem compiling - seems like a swig issue:
`BloomFilter_wrap.cxx:3171:55: error: no matching function for call to ‘BloomFilter::contains(const char*)’
     result = (bool)(arg1)->contains((char const *)arg2);
                                                       ^
BloomFilter_wrap.cxx:3171:55: note: candidates are:
In file included from BloomFilter_wrap.cxx:1998:0:
../BloomFilter.hpp:202:7: note: bool BloomFilter::contains(const std::vector<long unsigned int>&) const
  bool contains(vector<size_t> const &precomputed) const {
       ^
../BloomFilter.hpp:202:7: note:   no known conversion for argument 1 from ‘const char*’ to ‘const std::vector<long unsigned int>&’
../BloomFilter.hpp:216:7: note: bool BloomFilter::contains(const size_t*) const
  bool contains(const size_t precomputed[]) const {
       ^
../BloomFilter.hpp:216:7: note:   no known conversion for argument 1 from ‘const char*’ to ‘const size_t* {aka const long unsigned int*}’`

No amount of changing versions of swig and g++ could fix this. I had to go into BloomFilter.hpp and add another version of contains() and insert() that takes a const char*. Now it seems to be working smoothly.

**Comment by warrenlr** [comment]
great! I am glad it's working

**Comment by nathanweeks** [comment]
I encountered this issue as well using GCC 7.1.0. It seemed to be resolved by omitting the `-Dbool=char` option; i.e.:

```
g++ -c BloomFilter_wrap.cxx -I/usr/lib64/perl5/CORE -fPIC -Dbool=char
```
becomes
```
g++ -c BloomFilter_wrap.cxx -I/usr/lib64/perl5/CORE -fPIC
```
C++ already defines a "bool" type (and, at least with g++ on x86, sizeof(bool) == 1 like sizeof(char)).

**Comment by warrenlr** [comment]
thank you for the issue/solution @nathanweeks !
